### ISSUE TITLE
Cannot analyze messages because "no such file or directory @ rb_sysopen"

### ISSUE THREAD

**Issue by victorialo** [Lackoftactics/facebook_data_analyzer#22]
Upon trying to analyze messages using the command 
` $ DEBUG=true ruby analyze_facebook_data.rb /Users/victoria/Downloads/facebook-victorialo123`, I get this output:

```Analyzing Messages |Time: 00:00:00 | ======================================================================= | Time: 00:00:00
/Users/victoria/Documents/facebook_data_analyzer/classes/analyzeables/messages.rb:31:in `initialize': No such file or directory @ rb_sysopen - /Users/victoria/Downloads/facebook-victorialo123/index.htm (Errno::ENOENT)
	from /Users/victoria/Documents/facebook_data_analyzer/classes/analyzeables/messages.rb:31:in `open'```

messages.rb:31 points to the line
`@me ||= Nokogiri::HTML(File.open("#{@catalog}/index.htm")).title.split(' - Profile')[0].to_sym`

Might want to look into this. 

Thank you!

**Comment by thnukid** [comment]
@victorialo 
There was a discussion in #7 that there are different kind of archives exported. You might also have such an archive.

What would be great if you can provide the folder / file structure that you have, so that in future development these archives also can be supported.

If you can run this from your terminal and post the result in this issue, that would be great help:

> [ls -RGng](https://explainshell.com/explain?cmd=ls+-RGng) /Users/victoria/Downloads/facebook-victorialo123 > archive_list.txt

**Comment by victorialo** [comment]
![image](https://user-images.githubusercontent.com/4009775/39568543-669e59ce-4e77-11e8-8207-411b73e1cfa8.png)
Here's a screenshot of the folder structure of the downloaded data.

I looked at the creation of `archive_list.txt` and it contains some personal information, such as friends' names. Should I send this separately instead?

**Comment by thnukid** [comment]
@victorialo 
The friend names are sensitive information, so you want to keep that private.

What is currently parsed are these files:
`<facebook-archive>/html/friends.htm`
`<facebook-archive>/html/contact_info.htm`
`<facebook-archive>/html/friends.htm`
`<facebook-archive>/index.htm`

**Comment by victorialo** [comment]
Yeah, I'm looking, and I have no such folder called `<facebook-archive>/html` and I have `index.html` instead of `index.htm`. 

The `/messages/*.html` seems to exist just fine, though.

**Comment by thnukid** [comment]
Maybe because you have more information gathered the `html` directory is missing and split into folders.

`<facebook-archive>/html/contact_info.htm` might map to your `profile_information` folder
`<facebook-archive>/html/friends.htm` might map to your `friends` folder

What is the folder/file structure inside `profile_information` and `friends` folder?

**Comment by victorialo** [comment]
![image](https://user-images.githubusercontent.com/4009775/39637548-393fb214-4f78-11e8-9137-72519898d3a1.png)

![image](https://user-images.githubusercontent.com/4009775/39637559-410b505c-4f78-11e8-8624-97c09e0cd0ca.png)

**Comment by northcott-j** [comment]
@victorialo have you run without `DEBUG=true`? That needs to run at least once to parse the messages into .json files. After that, that flag can be used to avoid reading every message again. 

I'd remove the Contacts.new from the `analyzeables` array in `analyze_facebook_data.rb`.

I'd try updating the friends script to target `friends_added.html`.  If that doesn't work, I'd remove it from the array too. I'm not familiar with your folder structure, but it should at least work for messages.

**Comment by victorialo** [comment]
I removed `Contacts.new` and I've updated `initialize` in analyzeables/friends.rb to be the following. Am I doing it right?

``` ruby
def initialize(catalog:)
    @catalog = catalog
    # @directory = "#{catalog}/html/"
    # @file_pattern = 'friends.htm'
    @directory = "#{catalog}/friends/"
    @file_pattern = 'friends_added.html'
    @friends = []

    super()
  end
```

I still get
```
$ ruby analyze_facebook_data.rb /Users/victoria/Downloads/facebook-victorialo123
Parsing Messages |Time: 00:00:00 | ========================================================================= | Time: 00:00:00
Analyzing Messages |Time: 00:00:00 | ======================================================================= | Time: 00:00:00
/Users/victoria/Documents/facebook_data_analyzer/classes/analyzeables/messages.rb:96:in `count_by_sender': undefined method `each' for nil:NilClass (NoMethodError)
	from /Users/victoria/Documents/facebook_data_analyzer/classes/analyzeables/messages.rb:128:in `block in message_statistics_sheet'```

Removing the Friends feature also doesn't help:
```
$ ruby analyze_facebook_data.rb /Users/victoria/Downloads/facebook-victorialo123
Parsing Messages |Time: 00:00:00 | ========================================================================= | Time: 00:00:00
Analyzing Messages |Time: 00:00:00 | ======================================================================= | Time: 00:00:00
/Users/victoria/Documents/facebook_data_analyzer/classes/analyzeables/messages.rb:96:in `count_by_sender': undefined method `each' for nil:NilClass (NoMethodError)
	from /Users/victoria/Documents/facebook_data_analyzer/classes/analyzeables/messages.rb:128:in `block in message_statistics_sheet'
```
If you look at the error message, it's something wrong with messages.

**Comment by northcott-j** [comment]
@victorialo - you're right, it does look like the issue is with messages. Are there any .json files in your messages folder? If so, can you delete them and try again?

If that doesn't work, my guess is that the HTML structure of your conversations is different from other archives which will involve some refactoring to fix. It'd be nice if the different formats could be generalized so a user could specify the archive type as a command line arg.

**Comment by victorialo** [comment]
Yeah, there was a `_.messages.html.json` in that folder. I deleted it and tried again but got the same output, and the file was just recreated. 

Yeah, I was thinking that too - that would be nice. 

I could send you one of the files maybe to work off of to refactor?

**Comment by northcott-j** [comment]
I do not have a `messages.html` file in my `messages` folder. My `messages` folder looks like this. Does yours look similar?
<img width="855" alt="screen shot 2018-05-08 at 10 50 10 am" src="https://user-images.githubusercontent.com/9503623/39764459-a56c68be-52ad-11e8-9dfc-0cc7795d1c77.png">

I'm hoping that this issue is purely a directory structure one, and not that the individual files are also different. But if your html files are also different, having one would be super helpful for a refactor

**Comment by victorialo** [comment]
![image](https://user-images.githubusercontent.com/4009775/39765253-41879a92-5296-11e8-8c3c-e7afd909bd33.png)
Mine is quite a bit different from yours....

Some of the folders have a `photos`, some have a `files`, some have neither.

**Comment by thnukid** [comment]
@victorialo I have create PR #33 - maybe you can check out that branch and see if this removes all sensitive information from your export. 

Then @northcott-j and the others can deeper analyse your archive without posting screenshots.

**Comment by thnukid** [comment]
@victorialo can you run `bin/anonymized_facebook_export --catalog <your_facebook_export_directory> --export <anonymized_export_to_directory` and share the results with us (maybe my making a pull request).
