### ISSUE TITLE
Output not generated when script runs

### ISSUE THREAD

**Issue by ananthnann** [Lackoftactics/facebook_data_analyzer#35]
Hi, 

I've downloaded the script and the facebook zip file, but when I try to run the script with the data it does not produce an output (screenshot attached) 
![ruby analyzer no output](https://user-images.githubusercontent.com/38874239/41009147-cdbcf1fa-68f4-11e8-98c0-9038e339ff9e.PNG)
. 

It was originally giving me dependency errors like 

"C:/Ruby24-x64/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- parallel (LoadError)
        from C:/Ruby24-x64/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from facebook_data_analyzer.rb:6:in `<main>'"

 which i fixed by installing the required packages like axlsx and parallel individually.

I also had some errors like 

"C:/Ruby24-x64/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- facebook_data_analyzer/analyzeables/analyzeable (LoadError)
        from C:/Ruby24-x64/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from facebook_data_analyzer.rb:11:in `<main>'"

which I fixed by specifying the full path in facebook_data_analyzer.rb.

However, the latest issue is not producing any errors so I'm not sure how to proceed from here.

**Comment by ananthnann** [comment]
@Lackoftactics wasn't able to find the .xls file, don't think it was even created. I am on Windows though, I'll try to get access to an OSX/Linux machine and see if the script runs there. Thank you!
