### ISSUE TITLE
`count_by_sender': undefined method `each' for nil:NilClass

### ISSUE THREAD

**Issue by verdie-g** [Lackoftactics/facebook_data_analyzer#37]
Hi,

I get the following error when running `./bin/facebook_data_analyzer -c data_html`

```
Traceback (most recent call last):
	8: from ./bin/facebook_data_analyzer:34:in `<main>'
	7: from facebook_data_analyzer/lib/facebook_data_analyzer.rb:40:in `run'
	6: from facebook_data_analyzer/lib/facebook_data_analyzer.rb:40:in `each'
	5: from facebook_data_analyzer/lib/facebook_data_analyzer.rb:42:in `block in run'
	4: from facebook_data_analyzer/lib/facebook_data_analyzer/mixins/export_views_mixin.rb:13:in `export'
	3: from facebook_data_analyzer/lib/facebook_data_analyzer/mixins/export_views_mixin.rb:13:in `each'
	2: from facebook_data_analyzer/lib/facebook_data_analyzer/mixins/export_views_mixin.rb:14:in `block in export'
	1: from facebook_data_analyzer/lib/facebook_data_analyzer/view_model_generators/messages_view_model_generator.rb:230:in `message_statistics_view_model'
facebook_data_analyzer/lib/facebook_data_analyzer/messages.rb:101:in `count_by_sender': undefined method `each' for nil:NilClass (NoMethodError)
```

Tell me if I can give you more information.

**Comment by marekdlugos** [comment]
Just ran into the same issue. Any updates?

**Comment by verdie-g** [comment]
I've created a similar project [verdie-g/fb-data-analyzer](https://github.com/verdie-g/fb-data-analyzer). It only generates a json though.

**Comment by Lackoftactics** [comment]
@marekdlugos will try to look at it in spare time.

**Comment by BalintPogatsa** [comment]
I've created a pull request with the fixes that were working for my recently exported data from facebook.

https://github.com/Lackoftactics/facebook_data_analyzer/pull/39
